name: lint

on: 
  push:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run flake8 gendiff
      - run: poetry run pytest
      - name: Test coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: 9bb54c6806b1e21e766ca3e8f8f43a1834a56c197eb33e2549c80617b588393b
        with:
          coverageCommand: poetry run pytest --cov=gendiff.scripts
          debug: true
